### ISSUE TITLE
[v1.13.2] dataTables_processing background value broken

### ISSUE THREAD

**Issue by mdupont** [DataTables/Dist-DataTables-Bootstrap5#7]
See https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/1.13.2/css/dataTables.bootstrap5.css#L123

The processing indicator is not shown because the final CSS contains an invalid value for the `background` property in 1.13.2

```
  background: 13 110 253;
```

in 1.13.1 it was valid, with

```
  background: rgba(13, 110, 253, 0.9);
```

**Comment by AllanJard** [comment]
Hi - thanks for flagging this up. There are a couple of threads in the forum about it as well, [such as this one](https://datatables.net/forums/discussion/75552/when-loading-the-processing-animation-is-disappeared-in-1-13-2#latest). It is indeed an error and has been fixed in git, but not yet released. It will be soon!
